#!/usr/bin/env node
// Smoke-check src/generated/types.ts:
//   1. File exists and is non-empty
//   2. AUTOGENERATED banner present
//   3. Banner reports the expected openapi-typescript version
//
// The full drift gate (regenerate-and-diff against the contracts spec)
// runs in CI via .github/workflows/openapi-types-fresh.yml. This local
// check is fast feedback: if you forgot to regenerate after bumping the
// generator, you see it before pushing.

import { readFileSync } from "node:fs";

const EXPECTED_GENERATOR_VERSION = "7.13.0";
const TARGET = "src/generated/types.ts";

let content;
try {
  content = readFileSync(TARGET, "utf8").slice(0, 500);
} catch (err) {
  console.error(`✗ ${TARGET} missing or unreadable. Run: pnpm openapi:generate`);
  process.exit(1);
}

if (!content.includes("AUTOGENERATED")) {
  console.error(`✗ ${TARGET} missing AUTOGENERATED banner. Run: pnpm openapi:generate`);
  process.exit(1);
}

const m = content.match(/openapi-typescript@(\S+)/);
if (!m) {
  console.error(`✗ ${TARGET} AUTOGENERATED banner missing generator version line`);
  process.exit(1);
}

if (m[1] !== EXPECTED_GENERATOR_VERSION) {
  console.error(
    `✗ ${TARGET} was generated by openapi-typescript@${m[1]}, expected @${EXPECTED_GENERATOR_VERSION}`,
  );
  console.error(`  Run: pnpm openapi:generate`);
  console.error(`  Or bump EXPECTED_GENERATOR_VERSION in scripts/check_openapi_banner.mjs`);
  process.exit(1);
}

console.log(`✓ ${TARGET} fresh (openapi-typescript@${m[1]})`);
